
version: '3'

services:
  customer-service:
    build: ./customer-service
    ports:
      - "5000:5000"

  billing-service:
    build: ./billing-service
    ports:
      - "5001:5001"
    depends_on:
      - customer-service